# Generated by Django 3.1.2 on 2020-11-06 15:59

from django.db import migrations, models
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('checkin_api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_staff',
        ),
        migrations.AddField(
            model_name='customuser',
            name='date_of_birth',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='phone',
            field=phone_field.models.PhoneField(help_text='Contact phone number', max_length=31, null=True),
        ),
    ]
