# Generated by Django 3.1.2 on 2020-11-06 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkin_api', '0002_auto_20201106_1059'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_staff',
            field=models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status'),
        ),
    ]
