# Generated by Django 3.1.3 on 2020-11-12 04:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkin_api', '0004_location_review_service_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='name',
        ),
    ]
