# Generated by Django 3.1.3 on 2020-11-12 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkin_api', '0006_auto_20201111_2347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='end_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='start_date',
            field=models.DateField(null=True),
        ),
    ]
