# Generated by Django 3.1.3 on 2020-11-12 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkin_api', '0007_auto_20201111_2350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
