# Generated by Django 3.1.5 on 2021-02-08 19:16

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('checkin_api', '0009_auto_20201111_2358'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='location',
            options={'verbose_name_plural': 'LocationHehe'},
        ),
        migrations.AlterField(
            model_name='review',
            name='content',
            field=tinymce.models.HTMLField(),
        ),
    ]
