# Generated by Django 3.1.5 on 2021-02-08 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkin_api', '0010_auto_20210208_1416'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='location',
            options={'verbose_name_plural': 'Locations'},
        ),
    ]
