# Generated by Django 3.1.5 on 2021-02-08 20:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('checkin_api', '0011_auto_20210208_1417'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='staff_location',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='checkin_api.location', verbose_name='Locations'),
        ),
    ]
