# Generated by Django 3.1.5 on 2021-02-09 04:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('checkin_api', '0012_staff_staff_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='staff',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='review_staff_location', to='checkin_api.staff'),
        ),
    ]
