# Generated by Django 3.1.5 on 2021-02-11 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkin_api', '0013_auto_20210208_2355'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='location',
            options={},
        ),
    ]
