# Generated by Django 3.1.5 on 2021-02-13 22:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('checkin_api', '0014_auto_20210210_2325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='staff_location',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='staff_location', to='checkin_api.location', verbose_name='Locations'),
        ),
    ]
